### ISSUE TITLE
Not working in VSCode Multi Root Workspace

### ISSUE THREAD

**Issue by dasaveliev** [tintinweb/vscode-solidity-flattener#1]
https://github.com/microsoft/vscode/wiki/Adopting-Multi-Root-Workspace-APIs#eliminating-rootpath .
extension.js, Line 95: if (!isSubpath(vscode.workspace.rootPath, tpath)) will always return true which results in error in VSCode Multi Root Workspace due to deprecated vscode.workspace.rootPath.

**Comment by tintinweb** [comment]
Thanks for the report @dasaveliev 🙌 

Should be fixed with `0.0.8`. Let me know if you still get an error. 

cheers,
tin
