### ISSUE TITLE
Fails when code has unchecked block!

### ISSUE THREAD

**Issue by ErrorEater** [tintinweb/vscode-solidity-flattener#3]
Flattener fails when code has "unchecked" block coming with solidity ^0.8.0.

```
unchecked {
...
...
}
```

**Comment by tintinweb** [comment]
Hi aliveli186 

We rely on [truffle-flattener](https://www.npmjs.com/package/truffle-flattener) which is at the latest version. Seems like it might not be maintained anymore? Do you mind filing an issue upstream? You might also want to try the lexical flattener that is shipped with https://github.com/ConsenSys/vscode-solidity-auditor/releases/tag/v0.1.0

> new: use internal ("dumb" lexical) flattener by default. Optionally allow to select truffle-flattener (preferences → Settings → Solidity Visual Developer: solidity-va.flatten.mode)

**Comment by rothtty** [comment]
@tintinweb 
[truffle-flattener](https://www.npmjs.com/package/truffle-flattener) has updated its dependencies @solidity-parser/parser , I tested it fine with the latest truffle-flattener. 

Please update the project, thanks
